### ISSUE TITLE
support for custom kernel

### ISSUE THREAD

**Issue by akosinels** [Creeeeger/konaexynos#1]
Hi, I am currently at EvoX Android 15 Custom ROM with a custom kernel, tried building your app but it gives an error when I run it on my Samsung S10+ (Exynos 9820), it says:

Error

Failed when unpacking (Long press to copy)

FATAL ERROR: Couldn't open

"01_dtbdump_samsung,armv8.dtb": No such file or directory

chmod: 0.dts: No such file or directory

**Comment by Creeeeger** [comment]
Yes, sure, my bad.
The issue was very simple as well as dumb. 
Basically, when I coded it, I had Termux installed and so the required libs too. 
Now, you probably don’t have Termux installed and so don’t have the libs on your disk. 

The fix was by including them and improving the code handling in general.

Thank you very much for reporting the issue.
