### ISSUE TITLE
can't edit at 3rd reboot

### ISSUE THREAD

**Issue by akosinels** [Creeeeger/konaexynos#2]
![Screenshot_20241229-150308_KonaExynos.png](https://github.com/user-attachments/assets/b3b13aff-4a85-45b2-951c-711e1fb3070a)

I messed up and added frequency outside the recommended values, also instead of 12, it only let me add 11 frequency values.

now in fkm, this is what it shows:
![Screenshot_20241229-150505_Franco Kernel Manager.png](https://github.com/user-attachments/assets/4cdbcf11-74a6-4131-99f4-489c27e88d1d)

using s10+, freerunnerkernel, exoX A15

**Comment by Creeeeger** [comment]
Yes I fixed that Issue now.
thank you very much for reporting
was just that if the lines were not in order that it crashed then. should work fine now. 
tested out the new core as well
works fine too

for the limit of frequencies (the amount) I think 11. for the simple reason that the kernel cant handle more. if id remove the limit it would just say na for the frequencies

secondly for the higher frequencies, even tho they are possible in theory, and 1/2 in practice as my proof of concept shows it requires more messing around in the kernel itself since Samsung has some more barriers than just the tables from the sram themselves
